jobs:
- job: BuildOnUbuntu
  timeoutInMinutes: 10
  pool:
    name: 'Hosted Ubuntu 1604'
  variables:
    var1: 'hello var1'
    var2: 'hello var2'
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'env | sort'
- job: BuildOnWindows
  timeoutInMinutes: 10
  pool:
    name: 'Hosted VS2017'
  variables:
    var1: 'hello var1'
    var2: 'hello var2'
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'env | sort'
- job: BuildOnMacOS
  timeoutInMinutes: 10
  pool:
    name: 'Hosted VS2017'
  variables:
    var1: 'hello var1'
    var2: 'hello var2'
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'env | sort'